version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo Checking AWS CLI version in pre_build phase ...
      - aws --version
  build:
    commands:
      - echo Build started on `date`
      - aws s3 cp src/ s3://ahsan-s3/amazon-emr/ --recursive
  post_build:
    commands:
        - echo Finishing post_build phase
